### ISSUE TITLE
Ubuntu14 installation error

### ISSUE THREAD

**Issue by YichaoCaiDBS** [Ensembl/WiggleTools#18]
Hi,

I've trying to install wiggletools on my desktop. Followed the installation instructions, I installed all pre-requisite package but still can't install wiggletools.

This is the output when I run `sudo make`
```
mkdir -p bin
cd src; make -e
make[1]: Entering directory `/home/yichao/Documents/software/WiggleTools/src'
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c wiggleIterator.c -o wiggleIterator.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c wigReader.c -o wigReader.o
wigReader.c: In function ‘WiggleReaderSeek’:
wigReader.c:216:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bigWiggleReader.c -o bigWiggleReader.o
bigWiggleReader.c: In function ‘BigWiggleReaderSeek’:
bigWiggleReader.c:98:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c multiplexer.c -o multiplexer.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c reducers.c -o reducers.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bedReader.c -o bedReader.o
bedReader.c: In function ‘BedReaderSeek’:
bedReader.c:95:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bigBedReader.c -o bigBedReader.o
bigBedReader.c: In function ‘BigBedReaderSeek’:
bigBedReader.c:98:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bamReader.c -o bamReader.o
bamReader.c: In function ‘BamReaderSeek’:
bamReader.c:201:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c apply.c -o apply.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c commandParser.c -o commandParser.o
commandParser.c: In function ‘parseFile’:
commandParser.c:872:7: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(buffer, 1, length, file);
       ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c wigWriter.c -o wigWriter.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c statistics.c -o statistics.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c unaryOps.c -o unaryOps.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c multiSet.c -o multiSet.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c setComparisons.c -o setComparisons.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bufferedReader.c -o bufferedReader.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c vcfReader.c -o vcfReader.o
vcfReader.c: In function ‘VcfReaderSeek’:
vcfReader.c:70:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bcfReader.c -o bcfReader.o
bcfReader.c: In function ‘downloadBCFFile’:
bcfReader.c:53:3: warning: passing argument 2 of ‘pushValuesToBuffer’ discards ‘const’ qualifier from pointer target type [enabled by default]
   if (pushValuesToBuffer(data->bufferedReaderData, bcf_hdr_id2name(data->bcf_header, vcf_line->rid), vcf_line->pos+1, vcf_line->pos+2, 1))
   ^
In file included from bcfReader.c:19:0:
bufferedReader.h:26:6: note: expected ‘char *’ but argument is of type ‘const char *’
 bool pushValuesToBuffer(BufferedReaderData * data, char * chrom, int start, int finish, double value);
      ^
bcfReader.c: In function ‘BcfReaderSeek’:
bcfReader.c:94:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c plots.c -o plots.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c mWigWriter.c -o mWigWriter.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c recycleBin.c -o recycleBin.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c fib.c -o fib.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c samReader.c -o samReader.o
samReader.c: In function ‘SamReaderSeek’:
samReader.c:186:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
mkdir -p ../lib
ar rcs ../lib/libwiggletools.a *.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c wiggletools.c -o wiggletools.o
mkdir -p ../bin
cc -g -Wall -O3 -std=gnu99 -L../lib wiggletools.c -lwiggletools -lBigWig -lcurl -lhts -lgsl  -lgslcblas -lz -lpthread -lm -o ../bin/wiggletools 
make[1]: Leaving directory `/home/yichao/Documents/software/WiggleTools/src'
cd python/wiggletools; make
make[1]: Entering directory `/home/yichao/Documents/software/WiggleTools/python/wiggletools'
mkdir -p ../../bin
cp [^_]*.py *.sh ../../bin
make[1]: Leaving directory `/home/yichao/Documents/software/WiggleTools/python/wiggletools'
chmod 755 bin/*
```

When I run `sudo make test`, there is an error:
```
cd test; python2.7 test.py
Testing: ../bin/wiggletools do isZero diff fixedStep.bw variableStep.wig
../bin/wiggletools: error while loading shared libraries: libBigWig.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    assert test('../bin/wiggletools do isZero diff fixedStep.bw variableStep.wig') == 1
AssertionError
make: *** [tests] Error 1
```

Can you help me figure out what might went wrong? Thank you so much!

**Comment by obenno** [comment]
Hi,

I think this may be caused by your libBigwig, you sure it was well
installed?

Obenno

**Comment by YichaoCaiDBS** [comment]
I delete the libBigwig folder and install again. The output of the `make install` is :

```
cc -I. -g -Wall -O3 -Wsign-compare  -c -o io.o io.c
cc -I. -g -Wall -O3 -Wsign-compare  -c -o bwValues.o bwValues.c
cc -I. -g -Wall -O3 -Wsign-compare  -c -o bwRead.o bwRead.c
cc -I. -g -Wall -O3 -Wsign-compare  -c -o bwStats.o bwStats.c
cc -I. -g -Wall -O3 -Wsign-compare  -c -o bwWrite.o bwWrite.c
ar -rcs libBigWig.a io.o bwValues.o bwRead.o bwStats.o bwWrite.o
ranlib libBigWig.a
cc -I. -g -Wall -O3 -Wsign-compare  -fpic -c -o io.pico io.c
cc -I. -g -Wall -O3 -Wsign-compare  -fpic -c -o bwValues.pico bwValues.c
cc -I. -g -Wall -O3 -Wsign-compare  -fpic -c -o bwRead.pico bwRead.c
cc -I. -g -Wall -O3 -Wsign-compare  -fpic -c -o bwStats.pico bwStats.c
cc -I. -g -Wall -O3 -Wsign-compare  -fpic -c -o bwWrite.pico bwWrite.c
cc -shared  -o libBigWig.so io.pico bwValues.pico bwRead.pico bwStats.pico bwWrite.pico  -lcurl -lm -lz
install -d /usr/local/lib /usr/local/include
install libBigWig.a /usr/local/lib
install libBigWig.so /usr/local/lib
install *.h /usr/local/include
```
Still, the same error when I run `make test` in WiggleTools.

**Comment by obenno** [comment]
Could you print output of:

echo $LD_LIBRARY_PATH ?

**Comment by obenno** [comment]
If nothing out, pls add

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

to your .bashrc

**Comment by YichaoCaiDBS** [comment]
Hi Obenno,

I tried your suggestion. The `echo $LD_LIBRARY_PATH` is indeed empty. After add it to my bashrc file and resource. I delete the WiggleTools and run the installation again.

Still the same error both during installation and ` make test`
```
cd test; python2.7 test.py
Testing: ../bin/wiggletools do isZero diff fixedStep.bw variableStep.wig
../bin/wiggletools: error while loading shared libraries: libBigWig.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    assert test('../bin/wiggletools do isZero diff fixedStep.bw variableStep.wig') == 1
AssertionError
make: *** [tests] Error 1
```

**Comment by obenno** [comment]
Hi Yichao,

In previous installation,you got no error in the make step, right? Could
you print the error info you got this time in make step?

If you use sudo make install to install libBigWig, then there should be
libBigWig.so in /usr/local/lib, can you locate that file?

Obenno

**Comment by YichaoCaiDBS** [comment]
Hi Obenno,

The previous installation I got the same error as the one in the beginning of this thread. 
```
mkdir -p bin
cd src; make -e
make[1]: Entering directory `/home/yichao/Documents/software/WiggleTools/src'
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c wiggleIterator.c -o wiggleIterator.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c wigReader.c -o wigReader.o
wigReader.c: In function ‘WiggleReaderSeek’:
wigReader.c:216:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bigWiggleReader.c -o bigWiggleReader.o
bigWiggleReader.c: In function ‘BigWiggleReaderSeek’:
bigWiggleReader.c:98:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c multiplexer.c -o multiplexer.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c reducers.c -o reducers.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bedReader.c -o bedReader.o
bedReader.c: In function ‘BedReaderSeek’:
bedReader.c:95:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bigBedReader.c -o bigBedReader.o
bigBedReader.c: In function ‘BigBedReaderSeek’:
bigBedReader.c:98:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bamReader.c -o bamReader.o
bamReader.c: In function ‘BamReaderSeek’:
bamReader.c:201:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c apply.c -o apply.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c commandParser.c -o commandParser.o
commandParser.c: In function ‘parseFile’:
commandParser.c:872:7: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  fread(buffer, 1, length, file);
       ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c wigWriter.c -o wigWriter.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c statistics.c -o statistics.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c unaryOps.c -o unaryOps.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c multiSet.c -o multiSet.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c setComparisons.c -o setComparisons.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bufferedReader.c -o bufferedReader.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c vcfReader.c -o vcfReader.o
vcfReader.c: In function ‘VcfReaderSeek’:
vcfReader.c:70:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c bcfReader.c -o bcfReader.o
bcfReader.c: In function ‘downloadBCFFile’:
bcfReader.c:53:3: warning: passing argument 2 of ‘pushValuesToBuffer’ discards ‘const’ qualifier from pointer target type [enabled by default]
   if (pushValuesToBuffer(data->bufferedReaderData, bcf_hdr_id2name(data->bcf_header, vcf_line->rid), vcf_line->pos+1, vcf_line->pos+2, 1))
   ^
In file included from bcfReader.c:19:0:
bufferedReader.h:26:6: note: expected ‘char *’ but argument is of type ‘const char *’
 bool pushValuesToBuffer(BufferedReaderData * data, char * chrom, int start, int finish, double value);
      ^
bcfReader.c: In function ‘BcfReaderSeek’:
bcfReader.c:94:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c plots.c -o plots.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c mWigWriter.c -o mWigWriter.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c recycleBin.c -o recycleBin.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c fib.c -o fib.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c samReader.c -o samReader.o
samReader.c: In function ‘SamReaderSeek’:
samReader.c:186:14: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
mkdir -p ../lib
ar rcs ../lib/libwiggletools.a *.o
cc -g -Wall -O3 -std=gnu99  -D_PBGZF_USE -c wiggletools.c -o wiggletools.o
mkdir -p ../bin
cc -g -Wall -O3 -std=gnu99 -L../lib wiggletools.c -lwiggletools -lBigWig -lcurl -lhts -lgsl  -lgslcblas -lz -lpthread -lm -o ../bin/wiggletools 
make[1]: Leaving directory `/home/yichao/Documents/software/WiggleTools/src'
cd python/wiggletools; make
make[1]: Entering directory `/home/yichao/Documents/software/WiggleTools/python/wiggletools'
mkdir -p ../../bin
cp [^_]*.py *.sh ../../bin
make[1]: Leaving directory `/home/yichao/Documents/software/WiggleTools/python/wiggletools'
chmod 755 bin/*
```
I can locate the libBigWig.so in /usr/local/lib. But it seems that the test.py cant not find it.

Yichao

**Comment by obenno** [comment]
Hi Yichao,

If you got /usr/local/lib in your $LD_LIBRARY_PATH, and still get same
error, then I've no clue now, hope someone else could help~ Sorry cannot
help you fixing~

Obenno

**Comment by YichaoCaiDBS** [comment]
Hi Obenno

No worries. I will try to seek for others' advice. 
Thank you very much for your patience and help! 

PS: 
After I add `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` to the .bashrc, I echo the path and the output is:
```
/usr/local/lib:
```
Is that correct?

Thanks,
Yichao

**Comment by obenno** [comment]
Hi Yichao,

You're welcome.

It's correct, I'm using ubuntu 16.04, and it works well on my system. Will
keep on following the thread~

Obenno

**Comment by dzerbino** [comment]
Good morning @YichaoCaiDBS and @obenno!
Could you please check that there is a libBigWig.so file in /usr/local/lib?
* If not: failure in the installation procedure
* Else: failure in the linker.

**Comment by YichaoCaiDBS** [comment]
Hi @dzerbino 

There is libBigWig.so in /usr/local/lib. 
If this is failure of the linker, how should I do to get it right?

Thank you !
Yichao

**Comment by dzerbino** [comment]
What are the permissions on the libBigWig.so file? I see you ran some sudos, do users have permission to read and execute it?

**Comment by YichaoCaiDBS** [comment]
Hi @dzerbino ,

Sorry for late reply.

I've attached the output of ls under /usr/local/lib. Yes, the libBigWig.so is executable and readable by all users


```
-rwxr-xr-x  1 root root    390308 Jun  9 13:40 libBigWig.a
-rwxr-xr-x  1 root root    235210 Jun  9 13:40 libBigWig.so
-rw-r--r--  1 root root  19176040 Jun  9 11:17 libgsl.a
-rw-r--r--  1 root root   1758882 Jun  9 11:17 libgslcblas.a
-rwxr-xr-x  1 root root       949 Jun  9 11:17 libgslcblas.la
lrwxrwxrwx  1 root root        20 Jun  9 11:17 libgslcblas.so -> libgslcblas.so.0.0.0
lrwxrwxrwx  1 root root        20 Jun  9 11:17 libgslcblas.so.0 -> libgslcblas.so.0.0.0
-rwxr-xr-x  1 root root   1048362 Jun  9 11:17 libgslcblas.so.0.0.0
-rwxr-xr-x  1 root root       918 Jun  9 11:17 libgsl.la
lrwxrwxrwx  1 root root        16 Jun  9 11:17 libgsl.so -> libgsl.so.19.3.0
lrwxrwxrwx  1 root root        16 Jun  9 11:17 libgsl.so.19 -> libgsl.so.19.3.0
-rwxr-xr-x  1 root root  11353452 Jun  9 11:17 libgsl.so.19.3.0
-rw-r--r--  1 root root   5003244 Jun  9 11:02 libhts.a
lrwxrwxrwx  1 root root        27 Jun  9 11:16 libhts.so -> libhts.so.1.4.1-32-g5b9361d
-rw-r--r--  1 root root   3120855 Jun  9 11:02 libhts.so.1.4.1-32-g5b9361d
lrwxrwxrwx  1 root root        27 Jun  9 11:16 libhts.so.2 -> libhts.so.1.4.1-32-g5b9361d

```

Thank you!

**Comment by dzerbino** [comment]
Not exactly: libBigWig.so has 777 permissions, but it is a link to libhts.so.1.4.1-32-g5b9361d, which has 644 permissions. Could you please try `chmod 755 /usr/local/lib/libhts.so.1.4.1-32-g5b9361d`?

**Comment by YichaoCaiDBS** [comment]
Hi,
I tried the suggestion and reinstall WiggleTools again. Again the `make test` returns me the same error. 

Also, during installation there is one warning keeps occurring:
```
warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
  data->chrom = chrom;
              ^
```
And this warning occurs every time in the *ReaderSeek function in *Reader.c file.

**Comment by dzerbino** [comment]
Curious...

OK let's do this methodically. In the WiggleTools directory, when you type `ldd bin/wiggletools`, what do you get? This will allow us to understand what LD is doing at the moment.

**Comment by YichaoCaiDBS** [comment]
This is the output of `ldd bin/wiggletools` :

```
        linux-vdso.so.1 =>  (0x00007ffc3f30f000)
	libBigWig.so => /usr/local/lib/libBigWig.so (0x00007f0848327000)
	libhts.so.2 => /usr/local/lib/libhts.so.2 (0x00007f0848080000)
	libgsl.so.0 => /usr/lib/libgsl.so.0 (0x00007f0847c20000)
	libgslcblas.so.0 => /usr/local/lib/libgslcblas.so.0 (0x00007f08479e3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f08477c5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f08474bf000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f08470f7000)
	libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f0846e90000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0846c77000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f0846a67000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f0846845000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0848536000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f0846612000)
	librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007f08463f8000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f0846199000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f0845dbd000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f0845b76000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f0845967000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f0845716000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0845512000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f0845253000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f0844fd3000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f0844d08000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f0844ad9000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f08448d5000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f08446ca000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f08444af000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f0844294000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f0844056000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f0843e42000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f0843c00000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f08439fb000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f08437f7000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f08435ee000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f0843366000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f08430c5000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f0842e92000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f0842c7d000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f0842a75000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f084284c000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f084263e000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f08423f5000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f084213c000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f0841f03000)

```

**Comment by dzerbino** [comment]
Wait, so it does find libBigWig.so!

What happens if you simply type `./bin/wiggletools`?
Then `make test`?

**Comment by YichaoCaiDBS** [comment]
Wow! I don't know what happened. But I've passed the test!

However, if I type `wiggletools` elsewhere, the computer can't found the programe. So, do I need to add the path `path/to/bin/wiggletools` to environment path?

Thank you!

Output of `./bin/wiggletools`
```
WiggleTools

Copyright [1999-2017] EMBL-European Bioinformatics Institute
Development contact: Daniel Zerbino zerbino@ebi.ac.uk

Citation: Zerbino DR, Johnson N, Juettemann T, Wilder SP and Flicek PR: WiggleTools: parallel processing of large collections of genome-wide datasets for visualization and statistical analysis. Bioinformatics 2014 30:1008-1009.

This library parses wiggle files and executes various operations on them streaming through lazy evaluators.

Inputs:
	The program takes in Wig, BigWig, BedGraph, Bed, BigBed, Bam, VCF, and BCF files, which are distinguished thanks to their suffix (.wig, (.bw|.bigWig|.bigwig), .bg, .bed, .bb, .bam, .cram, .vcf, .bcf respectively).
	Note that wiggletools assumes that every bam file has an index .bai file next to it.

Outputs:
	The program outputs a wiggle file in stdout unless the output is squashed

Command line:
	wiggletools --help
	wiggletools program

Program grammar:
	program = (iterator) | do (iterator) | (extraction) | (statistic) | run (file)
	iterator = (in_filename) | (unary_operator) (iterator) | (binary_operator) (iterator) (iterator) | (reducer) (multiplex) | (setComparison) (multiplex_list) | print (output) (statistic)
	unary_operator = unit | coverage | write (output) | write_bg (ouput) | smooth (int) | abs | exp | ln | log (float) | pow (float) | offset (float) | scale (float) | gt (float) | lt (float) | default (float) | isZero | extend (int) | bin (int) | (statistic)
	output = (out_filename) | -
	in_filename = *.wig | *.bw | *.bed | *.bb | *.bg | *.bam | *.cram | *.vcf | *.bcf
	statistic = (statistic_function) (iterator) | ndpearson (multiplex) (multiplex)
	statistic_function = AUC | meanI | varI | minI | maxI | stddevI | CVI | energy (wavelength) | pearson (iterator)
	binary_operator = diff | ratio | overlaps | trim | noverlaps | nearest | apply (statistic) | fillIn
	reducer = cat | sum | product | mean | var | stddev | entropy | CV | median | min | max
	setComparison = ttest | ftest | wilcoxon
	multiplex_list = (multiplex) | (multiplex) : (multiplex_list)
	multiplex = (iterator_list) | map (unary_operator) (multiplex) | strict (multiplex)
	iterator_list = (iterator) | (iterator) : (iterator_list)
	extraction = profile (output) (int) (iterator) (iterator) | profiles (output) (int) (iterator) (iterator) | histogram (output) (width) (iterator_list) | mwrite (output) (multiplex) | mwrite_bg (output) (multiplex)
		| apply_paste (out_filename) (statistic) (bed_file) (iterator)

```

And then the test:
```
cd test; python2.7 test.py
Testing: ../bin/wiggletools do isZero diff fixedStep.bw variableStep.wig
Testing: ../bin/wiggletools diff fixedStep.bw variableStep.wig fixedStep.wig
Trailing tokens: the last tokens in your command were not read, check your syntax:
... fixedStep.wig
Testing: ../bin/wiggletools do isZero diff fixedStep.bw fixedStep.wig
Testing: ../bin/wiggletools do isZero offset -1 ratio variableStep.bw variableStep.wig
Testing: ../bin/wiggletools do isZero diff bam.bam pileup.bg
Testing: ../bin/wiggletools do isZero diff bam.bam cram.cram
[W::cram_populate_ref] Creating reference cache directory /home/yichao/.cache/hts-ref
This may become large; see the samtools(1) manual page REF_CACHE discussion
Testing: ../bin/wiggletools do isZero diff bam.bam sam.sam
Testing: cat sam.sam | ../bin/wiggletools do isZero diff bam.bam sam -
Testing: ../bin/wiggletools do isZero diff overlapping.bed overlapping.bb
Testing: ../bin/wiggletools do isZero diff variableStep.bw variableStep.wig
Testing: ../bin/wiggletools do isZero diff vcf.vcf bcf.bcf
Testing: ../bin/wiggletools do isZero diff sum fixedStep.bw fixedStep.bw : scale 2 fixedStep.bw
Testing: ../bin/wiggletools do isZero diff sum fixedStep.bw fixedStep.bw : sum fixedStep.bw fixedStep.bw 
Testing: ../bin/wiggletools do isZero diff ln fixedStep.bw sum map ln fixedStep.bw 
Testing: ../bin/wiggletools do isZero diff ln exp fixedStep.bw fixedStep.wig
Testing: ../bin/wiggletools do isZero diff pow 2 fixedStep.bw mult fixedStep.wig fixedStep.wig
Testing: ../bin/wiggletools do isZero diff lt 5 fixedStep.wig gt -5 scale -1 fixedStep.wig
Testing: ../bin/wiggletools apply_paste tmp/regional_means.txt meanI overlapping.bed fixedStep.wig
Testing: ../bin/wiggletools print tmp/pearson.txt pearson fixedStep.wig variableStep.wig
Testing: ../bin/wiggletools profiles tmp/profiles.txt 3 overlapping.bed fixedStep.wig
Testing: ../bin/wiggletools profile tmp/profile.txt 3 overlapping.bed fixedStep.wig
Testing: ../bin/wiggletools do isZero diff fixedStep.wig overlaps fixedStep.wig fixedStep.wig
Testing: ../bin/wiggletools write_bg tmp/nearest_overlapping.bg nearest variableStep.wig overlapping.bed
Testing: ../bin/wiggletools write_bg tmp/nearest_fixedStep.bg nearest variableStep.wig fixedStep.bw
Testing: ../bin/wiggletools print - minI fixedStep.wig
Testing: ../bin/wiggletools print - maxI fixedStep.wig
Testing: ../bin/wiggletools do isZero diff overlapping_coverage.wig coverage overlapping.bed
Testing: ../bin/wiggletools do isZero diff trim overlapping.bed variableStep.wig mult overlapping.bed variableStep.wig
Testing: ../bin/wiggletools run program.txt
Testing: diff tmp expected
All tests OK

```

**Comment by dzerbino** [comment]
Glad to hear it! 

You can either copy ./bin/wiggletools into a directory of your path or add the directory it is contained in onto your path.

All the best,

Daniel
